const express = require("express");
const app = express();
const router = express.Router();
const mainc=require("../controller/maincontroller");
const logc=require("../controller/logincontroller");
router.route("/").get(mainc.login);
router.route("/").post(logc.login);
router.route("/index").get(logc.ensure,mainc.index);
router.route("/signup").get(mainc.signup);
router.route("/signup").post(logc.signup);
router.route("/doctor").get(logc.ensure,mainc.doctor);
router.route("/hospital").get(logc.ensure,mainc.hospitals);
router.route("/Dentistry").get(logc.ensure,mainc.treatment);
router.route("/about-us").get(logc.ensure,mainc.about);
router.route("/tvastra-plus").get(logc.ensure,mainc.tvastraplus);
router.route("/query").get(logc.ensure,mainc.query);
router.route("/contact").get(logc.ensure,mainc.contact);
router.route("/FAQ").get(logc.ensure,mainc.faq);
router.route("/about-hospital").get(logc.ensure,mainc.abouthospital);
router.route("/doctor-profile").get(logc.ensure,mainc.doctorprofile);
module.exports=router;